// src/components/tag/tag-button.vue
<template>
	<span :class="classes">
		<dropdown-button icon="tag-nub" :label="label">
			<icon-button @click="onEdit" icon="edit" label="common.edit" />
			<icon-button
				@click="onRemove"
				icon="trash-2"
				label="common.remove"
				type="danger"
			/>
		</dropdown-button>
	</span>
</template>

<script>
import DropdownButton from '../control/dropdown-button';
import IconButton from '../control/icon-button';
import isTagColor from '@/util/tag-color';
import './tag-button.css';

export default {
	components: {DropdownButton, IconButton},
	computed: {
		classes() {
			return {
				[`color-${this.color}`]: true,
				'tag-button': true
			};
		}
	},
	methods: {
		onEdit() {
			this.$emit('edit-tag');
		},
		onRemove() {
			this.$emit('remove-tag');
		}
	},
	name: 'tag-button',
	props: {
		color: {
			default: 'none',
			type: String,
			validator: isTagColor
		},
		label: {required: true, type: String}
	}
};
</script>

// src/components/tag/tag-button.tsx
import * as React from 'react';
import classNames from 'classnames';
import {useTranslation} from 'react-i18next';
import {ButtonCard} from '../container/button-card';
import {DropdownButton} from '../control/dropdown-button';
import {IconButton} from '../control/icon-button';
import {Color} from '../../util/color';
import './tag-button.css';

export interface TagButtonProps {
	color: Color;
	name: string;
	onDelete: () => void;
	onEdit: () => void;
}

export const TagButton: React.FC<TagButtonProps> = props => {
	const {t} = useTranslation();

	return (
		<span className={classNames('tag-button', `color-${props.color}`)}>
			<DropdownButton icon="tag-nub" label={props.name}>
				<ButtonCard>
					<IconButton
						icon="edit"
						onClick={props.onEdit}
						label={t('common.edit')}
					/>
					<IconButton
						icon="trash-2"
						onClick={props.onDelete}
						label={t('common.delete')}
						variant="danger"
					/>
				</ButtonCard>
			</DropdownButton>
		</span>
	);
};
