// src/components/tag/tag-stripe.vue
<template>
	<div class="tag-stripe">
		<span
			v-for="stripe in stripes"
			:class="`color-${stripe.color}`"
			:key="stripe.name"
			:title="stripe.name"
		/>
	</div>
</template>

<script>
import './tag-stripe.css';

export default {
	computed: {
		stripes() {
			return this.tags.reduce((result, name) => {
				const color = this.tagColors[name];

				if (color) {
					result.push({color, name});
				}

				return result;
			}, []);
		}
	},
	name: 'tag-stripe',
	props: {
		tagColors: {required: true, type: Object},
		tags: {type: Array}
	}
};
</script>

// src/components/tag/tag-stripe.tsx
import * as React from 'react';
import {TagColors} from '../../store/stories';
import './tag-stripe.css';

export interface TagStripeProps {
	tagColors: TagColors;
	tags: string[];
}

export const TagStripe: React.FC<TagStripeProps> = React.memo(props => {
	return (
		<div className="tag-stripe">
			{props.tags.map(tag => (
				<span
					className={`color-${props.tagColors[tag]}`}
					key={tag}
					title={tag}
				/>
			))}
		</div>
	);
});
