// src/routes/story-stats/index.vue
<template>
	<div class="story-stats">
		<top-bar
			:back-route="`/stories/${this.story.id}`"
			:back-label="story.name"
		/>
		<main-content :title="$t('dialogs.storyStats.dialogTitle')">
			<table class="story-stats">
				<tr>
					<td>{{ stats.characters }}</td>
					<td v-t="'dialogs.storyStats.characters'" />
				</tr>
				<tr>
					<td>{{ stats.words }}</td>
					<td v-t="'dialogs.storyStats.words'" />
				</tr>
				<tr>
					<td>{{ stats.passages }}</td>
					<td v-t="'dialogs.storyStats.passages'" />
				</tr>
				<tr>
					<td>{{ stats.links }}</td>
					<td v-t="'dialogs.storyStats.links'" />
				</tr>
				<tr>
					<td>{{ stats.brokenLinks }}</td>
					<td v-t="'dialogs.storyStats.brokenLinks'" />
				</tr>
			</table>

			<!--p>This story was last changed at {{ lastUpdate.toLocaleString() }}.</p>
			<p>
				<span v-t="{path: 'The IFID of this story is {{ ifid }}.'}" />. (<a
					href="https://ifdb.tads.org/help-ifid"
					target="_blank"
					v-t="'What\'s an IFID?'"
				/>)
			</p-->
		</main-content>
	</div>
</template>

<script>
import TopBar from '@/components/container/top-bar';
import MainContent from '@/components/container/main-content';

export default {
	components: {MainContent, TopBar},
	computed: {
		stats() {
			return this.$store.getters['story/storyStats'](this.story.id);
		},
		story() {
			const result = this.$store.state.story.stories.find(
				s => s.id === this.$route.params.storyId
			);

			if (!result) {
				console.warn(
					`There is no story in the data store with ID "${this.$route.params.id}".`
				);

				// TODO: show error message to user instead.
			}

			return result;
		}
	},
	name: 'story-stats'
};
</script>

// src/dialogs/story-stats.tsx
import * as React from 'react';
import {useTranslation} from 'react-i18next';
import {DialogCard} from '../components/container/dialog-card';
import {storyStats, storyWithId, useStoriesContext} from '../store/stories';
import {DialogComponentProps} from './dialogs.types';
import './story-stats.css';

const dateFormatter = new Intl.DateTimeFormat([], {
	dateStyle: 'full',
	timeStyle: 'long'
});

export interface StoryStatsDialogProps extends DialogComponentProps {
	storyId: string;
}

export const StoryStatsDialog: React.FC<StoryStatsDialogProps> = props => {
	const {storyId, ...other} = props;
	const {t} = useTranslation();
	const {stories} = useStoriesContext();

	const story = storyWithId(stories, storyId);
	let content: React.ReactNode = null;

	// Only calculate stats if the dialog is expanded.

	if (!other.collapsed) {
		const stats = storyStats(story);

		content = (
			<>
				<p>
					{t('storyStats.lastUpdate', {
						date: dateFormatter.format(story.lastUpdate)
					})}
				</p>
				<p>
					{t('storyStats.ifid', {ifid: story.ifid})}&nbsp;
					<a href="https://ifdb.org/help-ifid" target="_blank" rel="noreferrer">
						{t('storyStats.ifidExplanation')}
					</a>
				</p>
				<table className="counts">
					<tbody>
						<tr>
							<td>{stats.characters}</td>
							<td>{t('storyStats.characters')}</td>
						</tr>
						<tr>
							<td>{stats.words}</td>
							<td>{t('storyStats.words')}</td>
						</tr>
						<tr>
							<td>{stats.passages}</td>
							<td>{t('storyStats.passages')}</td>
						</tr>
						<tr>
							<td>{stats.links.length}</td>
							<td>{t('storyStats.links')}</td>
						</tr>
						<tr>
							<td>{stats.brokenLinks.length}</td>
							<td>{t('storyStats.brokenLinks')}</td>
						</tr>
					</tbody>
				</table>
			</>
		);
	}

	return (
		<DialogCard
			{...other}
			className="story-stats-dialog"
			fixedSize
			headerLabel={t('storyStats.title')}
		>
			<div className="content">{content}</div>
		</DialogCard>
	);
};
