// src/components/control/code-area.tsx
import * as React from 'react';
import {
	Controlled as CodeMirror,
	IControlledCodeMirror
} from 'react-codemirror2';
import 'codemirror/lib/codemirror.css';
import 'codemirror/mode/css/css';
import 'codemirror/mode/javascript/javascript';
import './code-area.css';

// TODO: rework syntax highlights

export interface CodeAreaProps extends IControlledCodeMirror {
	fontFamily?: string;
	fontScale?: number;
	label?: string;
	value: string;
}

export const CodeArea: React.FC<CodeAreaProps> = props => {
	const {fontFamily, fontScale, label, ...otherProps} = props;
	const style: React.CSSProperties = {};

	if (fontFamily) {
		style.fontFamily = fontFamily.includes(' ')
			? `"${fontFamily}"`
			: fontFamily;
	}

	if (fontScale) {
		style.fontSize = `${fontScale * 100}%`;
	}

	return (
		<div className="code-area" style={style}>
			{label ? (
				<label>
					<span className="label">{label}</span>
					<CodeMirror {...otherProps} />
				</label>
			) : (
				<CodeMirror {...otherProps} />
			)}
		</div>
	);
};

// src/components/input/code-area.vue
<template>
	<div class="code-area">
		<label v-if="label">
			<span class="label" v-t="label" />
			<code-mirror @input="onChange" :options="{mode}" :value="value" />
		</label>
		<code-mirror @input="onChange" :options="{mode}" :value="value" v-else />
	</div>
</template>

<script>
import {codemirror as CodeMirror} from 'vue-codemirror';
import 'codemirror/lib/codemirror.css';
import 'codemirror/mode/css/css';
import 'codemirror/mode/javascript/javascript';
import './code-area.less';

export default {
	components: {CodeMirror},
	methods: {
		onChange(value) {
			this.$emit('change', value);
		}
	},
	name: 'code-area',
	props: {
		label: String,
		mode: String,
		value: String
	}
};
</script>
