// src/components/control/text-select.tsx
import * as React from 'react';
import classNames from 'classnames';
import './text-select.css';

export interface SelectOption {
	label: string;
	value: string;
}

export interface TextSelectProps {
	onChange?: React.ChangeEventHandler<HTMLSelectElement>;
	options: SelectOption[];
	orientation?: 'horizontal' | 'vertical';
	value: string;
}

export const TextSelect: React.FC<TextSelectProps> = props => {
	const {children, onChange, options, orientation, value} = props;
	const className = classNames(
		'text-select',
		`orientation-${orientation ?? 'horizontal'}`
	);

	return (
		<span className={className}>
			<label>
				<span className="text-select-label">{children}</span>
				<select onChange={onChange} value={value}>
					{options.map(option => (
						<option key={option.value} value={option.value}>
							{option.label}
						</option>
					))}
				</select>
			</label>
		</span>
	);
};

// src/components/input/text-select.vue
<template>
	<span :class="classes">
		<label>
			<span class="label"><slot></slot></span>
			<select @change="onChange" class="text-select" ref="select">
				<option
					v-for="(option, index) in options"
					:key="option"
					:selected="index === selectedIndex"
					>{{ option }}</option
				>
			</select>
		</label>
	</span>
</template>

<script>
import './text-select.less';

export default {
	computed: {
		classes() {
			return {
				'text-select': true,
				[`orientation-${this.orientation}`]: true
			};
		},
		selectedIndex() {
			return this.options.indexOf(this.value);
		}
	},
	methods: {
		onChange() {
			this.$emit('change', this.$refs.select.value);
		}
	},
	name: 'text-select',
	props: {
		options: {required: true, type: Array},
		orientation: {default: 'horizontal', type: String},
		value: {required: true, type: String}
	}
};
</script>
