// src/components/welcome/welcome-card.vue
<template>
	<base-card image-position="horizontal">
		<template v-slot:image><img :src="image" alt=""/></template>
		<template v-slot:header>{{ title }}</template>
		<slot></slot>
		<template v-slot:actions>
			<icon-button
				@click="onSkip"
				icon="fast-forward"
				label="common.skip"
				v-if="showSkip"
			/>
			<icon-button @click="onNext" icon="arrow-right" type="primary">{{
				nextLabel
			}}</icon-button>
		</template>
	</base-card>
</template>

<script>
import BaseCard from '../container/base-card';
import IconButton from '../control/icon-button';

export default {
	components: {BaseCard, IconButton},
	methods: {
		onNext() {
			this.$emit('next');
		},
		onSkip() {
			this.$emit('skip');
		}
	},
	name: 'welcome-card',
	props: {
		image: {
			required: true,
			type: String
		},
		nextLabel: {
			required: true,
			type: String
		},
		showSkip: {
			default: false,
			type: Boolean
		},
		title: {
			required: true,
			type: String
		}
	}
};
</script>

// src/components/welcome/welcome-card.tsx
import * as React from 'react';
import {useTranslation} from 'react-i18next';
import {CardFooter, CardBody, CardHeader, CardProps} from '../container/card';
import {ImageCard} from '../container/image-card';
import {IconButton} from '../control/icon-button';
import './welcome-card.css';

export interface WelcomeCardProps extends CardProps {
	image?: string;
	nextLabel: string;
	onNext: () => void;
	onSkip: () => void;
	showSkip: boolean;
	title: string;
}

export const WelcomeCard: React.FC<WelcomeCardProps> = props => {
	const {
		children,
		image,
		nextLabel,
		onNext,
		onSkip,
		showSkip,
		title,
		...otherProps
	} = props;
	const {t} = useTranslation();

	return (
		<div className="welcome-card">
			<ImageCard image={image && <img alt="" src={image} />} {...otherProps}>
				<CardHeader>{title}</CardHeader>
				<CardBody>{children}</CardBody>
				<CardFooter>
					{showSkip && (
						<IconButton
							icon="fast-forward"
							label={t('common.skip')}
							onClick={onSkip}
						/>
					)}
					<IconButton
						icon="arrow-right"
						variant="primary"
						onClick={onNext}
						label={nextLabel}
					/>
				</CardFooter>
			</ImageCard>
		</div>
	);
};
