// src/components/container/card-group.tsx
import * as React from 'react';
import './card-group.css';

export interface CardGroupProps {
	columns?: number;
	columnWidth?: string;
	maxWidth?: string;
}

export const CardGroup: React.FC<CardGroupProps> = props => {
	const {columns, columnWidth, maxWidth} = props;
	const style: React.CSSProperties = {
		gridTemplateColumns: columnWidth
			? `repeat(auto-fit, ${columnWidth})`
			: `repeat(${columns}, 1fr)`,
		maxWidth: maxWidth ?? 'auto'
	};

	return (
		<div className="card-group" style={style}>
			{props.children}
		</div>
	);
};

// src/components/container/card-group.vue
<template>
	<div class="card-group" :style="style"><slot></slot></div>
</template>

<script>
import './card-group.css';

export default {
	computed: {
		style() {
			return {
				'max-width': this.maxWidth,
				'grid-template-columns': this.columnWidth
					? `repeat(auto-fit, ${this.columnWidth})`
					: `repeat(${this.columnCount}, 1fr)`
			};
		}
	},
	name: 'card-group',
	props: {
		columnCount: {
			default: 4,
			type: Number
		},
		columnWidth: {
			type: String
		},
		maxWidth: {
			default: 'auto',
			type: String
		}
	}
};
</script>
