// src/routes/about-twine/index.vue
<template>
	<div class="about-twine">
		<top-bar back-route="/" :back-label="$t('storyList.title')" />
		<top-content
			:title="
				$t('aboutTwine.title', {
					buildNumber: this.buildNumber,
					version: this.version
				})
			"
		>
			<div class="app-info">
				<p v-t="'aboutTwine.twineDescription'" />
				<p v-t="'aboutTwine.license'" />
				<p>
					<icon-link
						href="https://twinery.org/donate"
						icon="heart"
						label="aboutTwine.donateToTwine"
						raised
					/>
					<icon-link
						href="https://github.com/klembot/twinejs"
						icon="code"
						label="aboutTwine.codeRepo"
						raised
					/>
				</p>
			</div>
			<div class="credits">
				<div class="credit-group">
					<h2 v-t="'aboutTwine.codeHeader'" />
					<ul>
						<li v-for="credit in credits.code" :key="`code-${credit}`">
							{{ credit }}
						</li>
					</ul>
				</div>
				<div class="credit-group">
					<h2 v-t="'aboutTwine.localizationHeader'" />
					<ul>
						<li
							v-for="credit in credits.localizations"
							:key="`localization-${credit}`"
						>
							{{ credit }}
						</li>
					</ul>
				</div>
			</div>
		</top-content>
	</div>
</template>

<script>
import IconLink from '@/components/input/icon-link';
import TopBar from '@/components/top-layout/top-bar';
import TopContent from '@/components/top-layout/top-content';
import credits from './credits.json';
import './index.less';

export default {
	components: {IconLink, TopBar, TopContent},
	computed: {
		buildVersion() {
			return this.$store.state.appInfo.appBuildVersion;
		},
		credits: () => credits,
		version() {
			return this.$store.state.appInfo.version;
		}
	},
	name: 'about-twine'
};
</script>

// src/dialogs/about-twine/about-twine.tsx
import * as React from 'react';
import {useTranslation} from 'react-i18next';
import {IconCode, IconHeart} from '@tabler/icons';
import {ButtonBar} from '../../components/container/button-bar';
import {DialogCard} from '../../components/container/dialog-card';
import {IconLink} from '../../components/control/icon-link';
import {getAppInfo} from '../../util/app-info';
import {DialogComponentProps} from '../dialogs.types';
import credits from './credits.json';
import './about-twine.css';

export const AboutTwineDialog: React.FC<DialogComponentProps> = props => {
	const {t} = useTranslation();
	const info = getAppInfo();

	return (
		<DialogCard
			{...props}
			className="about-twine-dialog"
			fixedSize
			headerLabel={t('dialogs.aboutTwine.title', {
				version: info.version
			})}
		>
			<div className="content">
				<p>{t('dialogs.aboutTwine.twineDescription')}</p>
				<p
					dangerouslySetInnerHTML={{
						__html: t('dialogs.aboutTwine.license')
					}}
				/>
				<div className="credits">
					<div className="code">
						<h3>{t('dialogs.aboutTwine.codeHeader')}</h3>
						<ul>
							{credits.code.map(c => (
								<li key={c}>{c}</li>
							))}
						</ul>
					</div>
					<div className="localizations">
						<h3>{t('dialogs.aboutTwine.localizationHeader')}</h3>
						<ul>
							{credits.localizations.map(c => (
								<li key={c}>{c}</li>
							))}
						</ul>
					</div>
				</div>
				<ButtonBar>
					<IconLink
						href="https://twinery.org/donate"
						icon={<IconHeart />}
						label={t('dialogs.aboutTwine.donateToTwine')}
						variant="primary"
					/>
					<IconLink
						href="https://github.com/klembot/twinejs"
						icon={<IconCode />}
						label={t('dialogs.aboutTwine.codeRepo')}
					/>
				</ButtonBar>
			</div>
		</DialogCard>
	);
};
