// src/components/passage/passage-toolbar.tsx
import * as React from 'react';
import classNames from 'classnames';
import {useTranslation} from 'react-i18next';
import {usePopper} from 'react-popper';
import {IconEdit, IconTool, IconTrash} from '@tabler/icons';
import {ButtonBar} from '../container/button-bar';
import {ButtonCard} from '../container/button-card';
import {IconButton} from '../control/icon-button';
import {Passage} from '../../store/stories';
import {boundingRect, rectCenter, Rect} from '../../util/geometry';
import './passage-toolbar.css';

export interface PassageToolbarProps {
	onDelete: () => void;
	onEdit: () => void;
	onTest: () => void;
	targets: Passage[];
	zoom: number;
}

export const PassageToolbar: React.FC<PassageToolbarProps> = React.memo(
	props => {
		const {onDelete, onEdit, onTest, targets, zoom} = props;
		const [forceInvisible, setForceInvisible] = React.useState(false);
		const [
			referenceElement,
			setReferenceElement
		] = React.useState<HTMLDivElement | null>(null);
		const [
			popperElement,
			setPopperElement
		] = React.useState<HTMLDivElement | null>(null);
		const {styles, attributes} = usePopper(referenceElement, popperElement, {
			modifiers: [
				{
					name: 'flip'
				}
			]
		});
		const {t} = useTranslation();

		// Force the popper to reposition as needed. We need to wait until any
		// passage drag is complete.

		React.useEffect(() => {
			setForceInvisible(true);

			const resetter = () => {
				if (document.body.classList.contains('dragging-passages')) {
					window.setTimeout(resetter, 25);
					return;
				}

				setForceInvisible(false);
			};

			Promise.resolve().then(resetter);
		}, [targets]);

		if (forceInvisible || targets.length === 0) {
			return null;
		}

		let targetRect: Rect = {height: 0, left: 0, top: 0, width: 0};

		if (targets.length === 1) {
			targetRect = {
				height: targets[0].height * zoom,
				left: targets[0].left * zoom,
				top: targets[0].top * zoom,
				width: targets[0].width * zoom
			};
		} else if (targets.length > 1) {
			// Position so that it's at the center of the selection.

			const center = rectCenter(boundingRect(targets));

			targetRect = {
				height: 0,
				left: center.left * zoom,
				top: center.top * zoom,
				width: 0
			};
		}

		const className = classNames('passage-toolbar', {
			multiple: targets.length > 1
		});

		return (
			<>
				<div
					aria-hidden
					className="passage-toolbar-target"
					ref={setReferenceElement}
					style={{...targetRect, ...styles}}
				></div>
				<div
					className={className}
					ref={setPopperElement}
					style={styles.popper}
					{...attributes.popper}
				>
					<ButtonCard floating>
						<ButtonBar>
							<IconButton
								icon={<IconTrash />}
								label={
									targets.length > 1
										? t('common.deleteCount', {count: targets.length})
										: t('common.delete')
								}
								onClick={onDelete}
								variant="danger"
							/>
							<IconButton
								icon={<IconEdit />}
								label={
									targets.length > 1
										? t('common.editCount', {count: targets.length})
										: t('common.edit')
								}
								onClick={onEdit}
							/>
							<IconButton
								disabled={targets.length > 1}
								icon={<IconTool />}
								label={t('common.test')}
								onClick={onTest}
							/>
						</ButtonBar>
					</ButtonCard>
				</div>
			</>
		);
	}
);

// src/components/passage/passage-toolbar.vue
<template>
	<div class="passage-toolbar-target-container" :style="targetContainerStyle">
		<hover-over allow-flip :visible="!forceInvisible && passages.length > 0">
			<div aria-hidden class="passage-toolbar-target" :style="targetStyle" />
			<template v-slot:hover>
				<div :class="toolbarClasses">
					<button-card>
						<button-bar>
							<icon-button
								@click="onTest"
								:disabled="passages.length > 1"
								icon="tool"
								label="common.test"
							/>
							<icon-button
								@click="onEdit"
								:disabled="passages.length > 1"
								icon="edit"
								label="common.edit"
							/>
							<icon-button @click="onDelete" icon="trash-2" type="danger">
								<span v-if="passages.length === 1" v-t="'common.delete'" />
								<span
									v-else
									v-t="{
										path: 'common.deleteCount',
										args: {count: passages.length}
									}"
								/>
							</icon-button>
						</button-bar>
					</button-card>
				</div>
			</template>
		</hover-over>
	</div>
</template>

<script>
import ButtonBar from '../container/button-bar';
import ButtonCard from '../container/button-card';
import HoverOver from '../container/hover-over';
import IconButton from '../control/icon-button';
import './passage-toolbar.css';

export default {
	components: {ButtonBar, ButtonCard, HoverOver, IconButton},
	computed: {
		target() {
			if (this.passages.length === 0) {
				return {};
			}

			if (this.passages.length === 1) {
				return {
					height: this.passages[0].height * this.zoom,
					left: this.passages[0].left * this.zoom,
					top: this.passages[0].top * this.zoom,
					width: this.passages[0].width * this.zoom
				};
			}

			/* Target the center of the selection. */

			let minX = Number.POSITIVE_INFINITY;
			let maxX = Number.NEGATIVE_INFINITY;
			let minY = Number.POSITIVE_INFINITY;
			let maxY = Number.NEGATIVE_INFINITY;

			this.passages.forEach(passage => {
				if (passage.top < minY) {
					minY = passage.top;
				}

				if (passage.top + passage.height > maxY) {
					maxY = passage.top + passage.height;
				}

				if (passage.left < minX) {
					minX = passage.left;
				}

				if (passage.left + passage.width > maxX) {
					maxX = passage.left + passage.width;
				}
			});

			return {
				height: 0,
				left: (minX + (maxX - minX) / 2) * this.zoom,
				top: (minY + (maxY - minY) / 2) * this.zoom,
				width: 0
			};
		},
		targetContainerStyle() {
			return {
				height: `${this.target.height}px`,
				left: `${this.target.left}px`,
				top: `${this.target.top}px`,
				width: `${this.target.width}px`
			};
		},
		targetStyle() {
			return {
				height: `${this.target.height}px`,
				width: `${this.target.width}px`
			};
		},
		toolbarClasses() {
			return {
				'passage-toolbar': true,
				single: this.passages.length === 1
			};
		}
	},
	data() {
		return {forceInvisible: false};
	},
	methods: {
		onDelete() {
			this.$emit('delete', this.passages);
		},
		onEdit() {
			this.$emit('edit', this.passages[0]);
		},
		onTest() {
			this.$emit('test', this.passages[0]);
		}
	},
	name: 'passage-toolbar',
	props: {
		passages: {type: Array},
		zoom: {required: true, type: Number}
	},
	watch: {
		target() {
			/*
			Force <hover-over> to reposition onscreen. We need to wait until any
			passage drag is done.
			*/

			this.forceInvisible = true;

			const resetter = () => {
				if (document.body.classList.contains('dragging-passages')) {
					window.setTimeout(resetter, 25);
					return;
				}

				this.forceInvisible = false;
			};

			this.$nextTick(resetter);
		}
	}
};
</script>
