// src/components/passage/passage-search-card.tsx
import * as React from 'react';
import {useTranslation} from 'react-i18next';
import {Card, CardActions, CardBody, CardHeader} from '../container/card';
import {IconButton} from '../control/icon-button';
import {PassageSearchResult} from '../../store/stories';

export interface PassageSearchCardProps extends PassageSearchResult {
	onEdit: () => void;
	onReplace: () => void;
}

export const PassageSearchCard: React.FC<PassageSearchCardProps> = props => {
	const {nameHighlighted, onEdit, onReplace, textHighlighted} = props;
	const {t} = useTranslation();

	return (
		<Card>
			<CardHeader>
				<span dangerouslySetInnerHTML={{__html: nameHighlighted}} />
			</CardHeader>
			<CardBody>
				<div dangerouslySetInnerHTML={{__html: textHighlighted}} />
			</CardBody>
			<CardActions>
				<IconButton
					icon="edit"
					label={t('components.passageSearchCard.editPassage')}
					onClick={onEdit}
				/>
				<IconButton
					icon="zap"
					label={t('components.passageSearchCard.replace')}
					onClick={onReplace}
					variant="danger"
				/>
			</CardActions>
		</Card>
	);
};

// src/components/passage/passage-search-card.vue
<template>
	<div class="passage-search-card">
		<base-card>
			<template v-slot:header>
				<span v-html="nameHighlighted" />
			</template>
			<div class="detail" v-if="expanded" v-html="textHighlighted" />
			<template v-slot:actions>
				<dropdown-button icon="more-horizontal" label="common.more">
					<icon-button
						@click="editPassage"
						icon="edit"
						label="components.passageSearchResult.editPassage"
					/>
					<icon-button
						@click="showPassage"
						icon="map-pin"
						label="components.passageSearchResult.showPassage"
					/>
				</dropdown-button>
				<icon-button
					@click="replaceInPassage"
					icon="zap"
					label="components.passageSearchResult.replace"
					type="danger"
				/>
			</template>
		</base-card>
	</div>
</template>

<script>
import BaseCard from '../container/base-card';
import DropdownButton from '../control/dropdown-button';
import IconButton from '../control/icon-button';
import './passage-search-card.css';

export default {
	components: {BaseCard, DropdownButton, IconButton},
	data() {
		return {expanded: true, menuVisible: false};
	},
	methods: {
		editPassage() {
			this.$emit('edit-passage', this.passage);
		},
		replaceInPassage() {
			this.$emit('replace-in-passage', this.passage);
		},
		showPassage() {
			this.$emit('show-passage', this.passage);
		},
		toggleExpanded() {
			this.expanded = !this.expanded;
		},
		toggleMenu() {
			this.menuVisible = !this.menuVisible;
		}
	},
	name: 'passage-search-result',
	props: {
		nameHighlighted: {required: true, type: String},
		passage: {required: true, type: Object},
		textHighlighted: {required: true, type: String},
		textMatches: {required: true, type: Number}
	}
};
</script>
