// src/routes/story-edit/top-bar/top-bar.tsx
import * as React from 'react';
import {useTranslation} from 'react-i18next';
import {useHistory} from 'react-router-dom';
import {Card} from '../../../components/container/card';
import {TopBar} from '../../../components/container/top-bar';
import {ControlledDropdownButton} from '../../../components/control/dropdown-button';
import {IconButton} from '../../../components/control/icon-button';
import {Story} from '../../../store/stories';
import {useDialogsContext} from '../dialogs';
import {useStoryLaunch} from '../../../store/use-story-launch';
import {Point} from '../../../util/geometry';
import {CreatePassageButton} from './create-passage-button';
import {HighlightField} from './highlight-field';
import {PublishToFileButton} from './publish-to-file-button';
import {RenameStoryButton} from './rename-story-button';
import {SelectAllPassagesButton} from './select-all-passages-button';
import {SetStoryFormatButton} from './set-story-format-button/set-story-format-button';
import {SnapToGridButton} from './snap-to-grid-button';
import {ZoomButtons} from './zoom-buttons';

export interface StoryEditTopBarProps {
	getCenter: () => Point;
	story: Story;
}

export const StoryEditTopBar: React.FC<StoryEditTopBarProps> = props => {
	const {getCenter, story} = props;
	const [menuOpen, setMenuOpen] = React.useState(false);
	const {dispatch} = useDialogsContext();
	const {playStory, proofStory, testStory} = useStoryLaunch();
	const history = useHistory();
	const {t} = useTranslation();

	function toggleMenu() {
		setMenuOpen(open => !open);
	}

	function runAndCloseMenu(callback: () => void) {
		callback();
		setMenuOpen(false);
	}

	return (
		<TopBar>
			<IconButton
				icon="arrow-left"
				label={t('storyList.title')}
				onClick={() => history.push('/')}
				variant="primary"
			/>
			<CreatePassageButton getCenter={getCenter} story={story} />
			<ZoomButtons story={story} />
			<IconButton
				icon="play"
				label={t('common.play')}
				onClick={() => runAndCloseMenu(() => playStory(story.id))}
			/>
			<IconButton
				icon="tool"
				label={t('common.test')}
				onClick={() => runAndCloseMenu(() => testStory(story.id))}
			/>
			<ControlledDropdownButton
				icon="more-horizontal"
				label={t('common.more')}
				onClick={toggleMenu}
				open={menuOpen}
			>
				<Card>
					<IconButton
						icon="search"
						label={t('storyEdit.topBar.findAndReplace')}
						onClick={() => history.push(`/stories/${story.id}/search`)}
					/>
					<SelectAllPassagesButton story={story} />
					<IconButton
						icon="bar-chart-2"
						label={t('storyEdit.topBar.storyStats')}
						onClick={() => history.push(`/stories/${story.id}/stats`)}
					/>
					<PublishToFileButton story={story} />
					<IconButton
						icon="book-open"
						label={t('storyEdit.topBar.proofStory')}
						onClick={() => runAndCloseMenu(() => proofStory(story.id))}
					/>
					<RenameStoryButton
						onCancelRename={() => setMenuOpen(false)}
						onRename={() => setMenuOpen(false)}
						story={story}
					/>
					<SnapToGridButton onChange={() => setMenuOpen(false)} story={story} />
					<SetStoryFormatButton
						onCancelChange={() => setMenuOpen(false)}
						story={story}
					/>
					<IconButton
						icon="code"
						label={t('storyEdit.topBar.editJavaScript')}
						onClick={() =>
							runAndCloseMenu(() =>
								dispatch({type: 'addStoryJavaScriptEditor'})
							)
						}
					/>
					<IconButton
						icon="hash"
						label={t('storyEdit.topBar.editStylesheet')}
						onClick={() => history.push(`/stories/${story.id}/stylesheet`)}
					/>
				</Card>
			</ControlledDropdownButton>
			<HighlightField story={story} />
		</TopBar>
	);
};

// src/routes/story-edit/top-bar/index.vue
<template>
	<div class="story-edit-top-bar">
		<top-bar back-route="/" :back-label="$t('storyList.title')">
			<template v-slot:actions>
				<icon-button
					@click="createPassage"
					icon="plus-circle"
					label="storyEdit.topBar.addPassage"
					type="create"
				/>
				<icon-button
					@click="zoomIn"
					icon="zoom-in"
					label="storyEdit.topBar.zoomIn"
				/>
				<icon-button
					@click="zoomOut"
					icon="zoom-out"
					label="storyEdit.topBar.zoomOut"
				/>
				<icon-button @click="testStory" icon="tool" label="common.test" />
				<icon-button @click="playStory" icon="play" label="common.play" />
				<dropdown-button icon="more-horizontal" label="common.more">
					<icon-button
						@click="editJavaScript"
						icon="code"
						label="storyEdit.topBar.editJavaScript"
					/>
					<icon-button
						@click="editStylesheet"
						icon="hash"
						label="storyEdit.topBar.editStylesheet"
					/>
					<icon-button
						icon="file-text"
						label="storyEdit.topBar.setStoryFormat"
					/>
					<icon-button
						@click="toggleRenamePrompt"
						icon="type"
						label="storyEdit.topBar.renameStory"
					/>
					<icon-button
						@click="selectAllPassages"
						icon="layers"
						label="storyEdit.topBar.selectAllPassages"
					/>
					<icon-button
						@click="findAndReplace"
						icon="search"
						label="storyEdit.topBar.findAndReplace"
					/>
					<icon-button
						@click="toggleSnapToGrid"
						:icon="story.snapToGrid ? 'check' : 'empty'"
						label="storyEdit.topBar.snapToGrid"
					/>
					<icon-button
						icon="bar-chart-2"
						@click="showStoryStats"
						label="storyEdit.topBar.storyStats"
					/>
					<icon-button
						@click="proofStory"
						icon="book-open"
						label="storyEdit.topBar.proofStory"
					/>
					<icon-button icon="download" label="common.publishToFile" />
				</dropdown-button>
				<text-line placeholder="Quick Find" />
			</template>
		</top-bar>
		<top-prompt
			@cancel="toggleRenamePrompt"
			:message="$t('storyEdit.topBar.renameStoryPrompt', {name: story.name})"
			@submit="renameStory"
			:visible="showRenamePrompt"
		/>
	</div>
</template>

<script>
import DropdownButton from '@/components/input/dropdown-button';
import IconButton from '@/components/input/icon-button';
import TextLine from '@/components/input/text-line';
import TopBar from '@/components/main-layout/top-bar';
import TopPrompt from '@/components/main-layout/top-prompt';
import openUrl from '@/util/open-url';
import '@/styles/accessibility.less';

export default {
	components: {
		DropdownButton,
		IconButton,
		TextLine,
		TopBar,
		TopPrompt
	},
	data() {
		return {findModalOpen: false, highlightText: '', showRenamePrompt: false};
	},
	methods: {
		createPassage() {
			this.$emit('create-passage');
		},
		editJavaScript() {
			this.$router.push(`/stories/${this.story.id}/javascript`);
		},
		editStylesheet() {
			this.$router.push(`/stories/${this.story.id}/stylesheet`);
		},
		findAndReplace() {
			this.$router.push(`/stories/${this.story.id}/search`);
		},
		playStory() {
			openUrl(`/stories/${this.story.id}/play`);
		},
		proofStory() {
			openUrl(`/stories/${this.story.id}/proof`);
		},
		testStory() {
			openUrl(`/stories/${this.story.id}/test`);
		},
		renameStory(value) {
			this.$store.dispatch('story/updateStory', {
				storyId: this.story.id,
				storyProps: {name: value}
			});
			this.toggleRenamePrompt();
		},
		selectAllPassages() {
			this.$store.dispatch('story/selectAllPassages', {
				storyId: this.story.id
			});
		},
		showStoryStats() {
			this.$router.push(`/stories/${this.story.id}/statistics`);
		},
		toggleFindModal() {
			this.findModalOpen = !this.findModalOpen;
		},
		toggleRenamePrompt() {
			this.showRenamePrompt = !this.showRenamePrompt;
		},
		toggleSnapToGrid() {
			this.$store.dispatch('story/updateStory', {
				storyId: this.story.id,
				storyProps: {snapToGrid: !this.story.snapToGrid}
			});
		},
		zoomIn() {
			this.$store.dispatch('story/changeZoom', {
				change: 0.1,
				storyId: this.story.id
			});
		},
		zoomOut() {
			this.$store.dispatch('story/changeZoom', {
				change: -0.1,
				storyId: this.story.id
			});
		}
	},
	name: 'story-edit-top-bar',
	props: {
		story: {
			required: true,
			type: Object
		}
	},
	watch: {
		highlightText(value) {
			this.$store.dispatch('story/highlightPassagesWithText', {
				search: value,
				storyId: this.story.id
			});
		}
	}
};
</script>
