// src/routes/story-edit/dialogs/passage-dialog/tag-toolbar.tsx
import * as React from 'react';
import {useTranslation} from 'react-i18next';
import {ButtonBar} from '../../../../components/container/button-bar';
import {IconButton} from '../../../../components/control/icon-button';
import {TagModal} from '../../../../components/tag/tag-modal';
import {
	addPassageTag,
	removePassageTag,
	renameTag,
	setTagColor,
	useStoriesContext,
	Passage,
	Story
} from '../../../../store/stories';
import {TagButton} from '../../../../components/tag/tag-button';
import {Color} from '../../../../util/color';

export interface TagToolbarProps {
	passage: Passage;
	story: Story;
}

// TODO: add explanation of what tags do

export const TagToolbar: React.FC<TagToolbarProps> = props => {
	const {passage, story} = props;
	const {dispatch} = useStoriesContext();
	const [newModalOpen, setNewModalOpen] = React.useState(false);
	const [newColor, setNewColor] = React.useState<Color>('none');
	const [newName, setNewName] = React.useState('');
	const [editModalOpen, setEditModalOpen] = React.useState(false);
	const [editColor, setEditColor] = React.useState<Color>('none');
	const [preEditName, setPreEditName] = React.useState('');
	const [editName, setEditName] = React.useState('');
	const {t} = useTranslation();

	function toggleNewModal() {
		if (!newModalOpen) {
			setNewColor('none');
			setNewName('');
		}

		setNewModalOpen(!newModalOpen);
	}

	function handleAddNewTag() {
		addPassageTag(dispatch, story, passage, newName);
		setTagColor(dispatch, story, newName, newColor);
		toggleNewModal();
	}

	function openEditModal(name: string, color?: Color) {
		setPreEditName(name);
		setEditName(name);
		setEditColor(color ?? 'none');
		setEditModalOpen(true);
	}

	function handleRemoveTag(name: string) {
		removePassageTag(dispatch, story, passage, name);
	}

	function handleEditTag() {
		renameTag(dispatch, story, preEditName, editName);
		setTagColor(dispatch, story, editName, editColor);
		setEditModalOpen(false);
	}

	return (
		<>
			<ButtonBar orientation="horizontal">
				<IconButton
					icon="plus"
					label={t('common.tag')}
					onClick={toggleNewModal}
					variant="create"
				/>
				{props.passage.tags.map(tag => (
					<TagButton
						color={props.story.tagColors[tag] ?? 'none'}
						key={tag}
						name={tag}
						onDelete={() => handleRemoveTag(tag)}
						onEdit={() => openEditModal(tag, props.story.tagColors[tag])}
					/>
				))}
			</ButtonBar>
			<TagModal
				color={newColor}
				isOpen={newModalOpen}
				message={t('passageEdit.tagToolbar.addTagHeader')}
				name={newName}
				onChangeName={setNewName}
				onChangeColor={setNewColor}
				onCancel={toggleNewModal}
				onSubmit={handleAddNewTag}
			/>
			<TagModal
				color={editColor}
				detail={t('passageEdit.tagToolbar.editTagDetail')}
				isOpen={editModalOpen}
				message={t('passageEdit.tagToolbar.editTagHeader')}
				name={editName}
				onChangeName={setEditName}
				onChangeColor={setEditColor}
				onCancel={() => setEditModalOpen(false)}
				onSubmit={handleEditTag}
			/>
		</>
	);
};

// src/routes/passage-edit/tag-toolbar.vue
<template>
	<div class="tag-toolbar">
		<button-bar>
			<icon-button
				@click="toggleAddTag"
				icon="plus"
				label="common.tag"
				type="create"
			/>
			<tag-button
				v-for="tag in passage.tags"
				:color="tagColors[tag]"
				@edit-tag="onStartEditTag({color: tagColors[tag], name: tag})"
				:key="tag"
				:label="tag"
				@remove-tag="onRemoveTag(tag)"
			/>
		</button-bar>
		<tag-modal
			@cancel="toggleAddTag"
			@submit="onAddTag"
			submit-icon="plus"
			submit-label="common.add"
			submit-type="create"
			:visible="addTagVisible"
		>
			<template v-slot:header>{{
				$t('passageEdit.tagToolbar.addTagHeader')
			}}</template>
		</tag-modal>
		<tag-modal
			@cancel="toggleEditTag"
			:default-color="editingTagColor"
			:default-name="editingTagName"
			@submit="onEditTag"
			:visible="editTagVisible"
		>
			<template v-slot:header>{{
				$t('passageEdit.tagToolbar.editTagHeader')
			}}</template>
			<template v-slot:detail
				><p v-t="'passageEdit.tagToolbar.editTagDetail'" />
			</template>
		</tag-modal>
	</div>
</template>

<script>
import ButtonBar from '@/components/container/button-bar';
import IconButton from '@/components/control/icon-button';
import TagButton from '@/components/tag/tag-button';
import TagModal from '@/components/tag/tag-modal';
import isTagColor from '@/util/tag-color';

export default {
	components: {ButtonBar, IconButton, TagButton, TagModal},
	data() {
		return {
			addTagVisible: false,
			editTagVisible: false,
			editingTagColor: undefined,
			editingTagName: undefined
		};
	},
	methods: {
		onAddTag({color, name}) {
			this.addTagVisible = false;
			this.$emit('add-tag', {color, name});
		},
		onEditTag({color, name}) {
			this.$emit('edit-tag', {
				newColor: color,
				newName: name,
				oldColor: this.editingTagColor,
				oldName: this.editingTagName
			});
			this.toggleEditTag();
		},
		onStartEditTag({color, name}) {
			this.editingTagColor = color;
			this.editingTagName = name;
			this.toggleEditTag();
		},
		onRemoveTag(name) {
			this.$emit('remove-tag', name);
		},
		toggleAddTag() {
			this.addTagVisible = !this.addTagVisible;
		},
		toggleEditTag() {
			this.editTagVisible = !this.editTagVisible;
		}
	},
	name: 'tag-toolbar',
	props: {
		passage: {required: true, type: Object},
		tagColors: {
			required: true,
			validator: value =>
				Object.keys(value).every(key => isTagColor(value[key]))
		}
	}
};
</script>
