// src/components/modal/confirm-modal.vue
<template>
	<base-modal :ariaLabelId="ariaLabelId" @close="onCancel" :visible="visible">
		<div class="confirm-modal">
			<base-card>
				<template v-slot:header
					><span :id="ariaLabelId">{{ message }}</span></template
				>
				<p v-if="detail">{{ detail }}</p>
				<template v-slot:actions>
					<icon-button @click="onCancel" icon="x" label="common.cancel" />
					<icon-button
						@click="onConfirm"
						:icon="confirmIcon"
						:label="confirmLabel"
						:type="confirmType"
					/>
				</template>
			</base-card>
		</div>
	</base-modal>
</template>

<script>
import BaseCard from '../container/base-card';
import BaseModal from './base-modal';
import IconButton from '../control/icon-button';
import './confirm-modal.css';

export default {
	components: {BaseCard, BaseModal, IconButton},
	computed: {
		ariaLabelId() {
			return this.domId + '-header';
		}
	},
	methods: {
		onCancel() {
			this.$emit('cancel');
		},
		onConfirm() {
			this.$emit('confirm');
		}
	},
	name: 'confirm-modal',
	props: {
		confirmIcon: {default: 'check', type: String},
		confirmLabel: {default: 'common.ok', type: String},
		confirmType: {default: 'primary', type: String},
		detail: {type: String},
		domId: {required: true, type: String},
		message: {required: true, type: String},
		visible: {type: Boolean}
	}
};
</script>

// src/components/modal/confirm-modal.tsx
import * as React from 'react';
import {useTranslation} from 'react-i18next';
import {Card, CardActions, CardBody, CardHeader} from '../container/card';
import {IconButton, IconButtonProps} from '../control/icon-button';
import {Modal, ModalProps} from './modal';
import './confirm-modal.css';

export interface ConfirmModalProps extends ModalProps {
	cancelButtonProps?: Partial<IconButtonProps>;
	confirmButtonProps?: Partial<IconButtonProps>;
	detail?: string;
	domId: string;
	message: string;
	onCancel: () => void;
	onConfirm: () => void;
}

export const ConfirmModal: React.FC<ConfirmModalProps> = props => {
	const {
		cancelButtonProps,
		confirmButtonProps,
		detail,
		domId,
		message,
		onCancel,
		onConfirm,
		...otherProps
	} = props;
	const {t} = useTranslation();

	return (
		<Modal {...otherProps}>
			<div className="confirm-modal">
				<Card>
					<CardHeader>{message}</CardHeader>
					<CardBody>{detail}</CardBody>
					<CardActions>
						<IconButton
							icon="x"
							label={t('common.cancel')}
							onClick={onCancel}
							{...cancelButtonProps}
						/>
						<IconButton
							icon="check"
							label={t('common.ok')}
							onClick={onConfirm}
							{...confirmButtonProps}
						/>
					</CardActions>
				</Card>
			</div>
		</Modal>
	);
};
