// src/components/story-format/story-format-card.vue
<template>
	<div class="story-format-card">
		<base-card image-position="horizontal" :selected="selected">
			<template v-slot:image>
				<icon-image name="clock" v-if="loadState === 'pending'" />
				<icon-image name="alert-triangle" v-if="loadState === 'failed'" />
				<template v-if="loadState === 'loaded'">
					<img
						:src="imageUrl"
						v-if="format.properties && format.properties.image"
					/>
					<icon-image name="file-text" v-else />
				</template>
			</template>
			<template v-slot:header>
				<span
					class="title"
					v-t="{
						path: 'components.storyFormatItem.name',
						args: {name: format.name, version: format.version}
					}"
				/>
			</template>
			<p
				class="author"
				v-if="loadState === 'loaded' && format.properties.author"
				v-t="{
					path: 'components.storyFormatItem.author',
					args: {author: format.properties.author}
				}"
			/>
			<div
				class="properties"
				v-html="format.properties.description"
				v-if="loadState === 'loaded'"
			/>
			<div class="error" v-if="loadState === 'failed'">
				<p
					v-t="{
						path: 'components.storyFormatItem.loadError',
						args: {error: format.loadError}
					}"
				/>
			</div>
			<div
				class="loading"
				v-if="loadState === 'pending'"
				v-t="components.storyFormatItem.loading"
			/>
			<template v-slot:actions v-if="loadState === 'loaded' && !selected">
				<icon-button
					@click="onRemove"
					icon="trash-2"
					label="common.remove"
					type="danger"
					v-if="canRemove"
				/>
				<icon-button
					:active="selected"
					@click="onSelect"
					icon="check"
					type="primary"
					>{{ selectLabel }}</icon-button
				>
			</template>
		</base-card>
	</div>
</template>

<script>
import BaseCard from '../container/base-card';
import IconButton from '../control/icon-button';
import IconImage from '../icon-image';
import './story-format-card.css';

export default {
	components: {BaseCard, IconButton, IconImage},
	computed: {
		loadState() {
			if (this.format.loadError) {
				return 'failed';
			}

			if (this.format.properties) {
				return 'loaded';
			}

			return 'pending';
		},
		imageUrl() {
			return this.format.userAdded
				? ''
				: process.env.BASE_URL +
						this.format.url.replace(/\/[^/]*?$/, '/') +
						this.format.properties.image;
		}
	},
	methods: {
		onRemove() {
			this.$emit('remove', this.format);
		},
		onSelect() {
			this.$emit('select', this.format);
		}
	},
	name: 'story-format-item',
	props: {
		canRemove: {default: false, type: Boolean},
		format: {required: true, type: Object},
		selectLabel: {required: true, type: String},
		selected: {default: false, type: Boolean}
	}
};
</script>

// src/components/story-format/story-format-card/story-format-card.tsx
import * as React from 'react';
import {useTranslation} from 'react-i18next';
import {Icon} from '../../image/icon/icon';
import {CardBody, CardHeader} from '../../container/card';
import {ImageCard} from '../../container/image-card';
import {IconButton} from '../../control/icon-button';
import {formatImageUrl, StoryFormat} from '../../../store/story-formats';
import {StoryFormatCardActions} from './story-format-card-actions';
import {StoryFormatCardDetails} from './story-format-card-details';
import './story-format-card.css';

export interface StoryFormatCardProps {
	format: StoryFormat;
	onDelete: () => void;
	onSelect: () => void;
	selected: boolean;
	selectedText?: string;
	selectIcon?: string;
	selectLabel?: string;
}

export const StoryFormatCard: React.FC<StoryFormatCardProps> = props => {
	const {
		format,
		onDelete,
		onSelect,
		selected,
		selectIcon,
		selectLabel
	} = props;
	const {t} = useTranslation();

	let image = <></>;

	if (format.loadState === 'error') {
		image = <Icon icon="alert-triangle" />;
	} else if (
		format.loadState === 'unloaded' ||
		format.loadState === 'loading'
	) {
		image = <Icon icon="loading-spinner" />;
	} else if (format.loadState === 'loaded' && format.properties.image) {
		image = <img src={formatImageUrl(format)} alt="" />;
	}

	return (
		<div className="story-format-card">
			<ImageCard image={image} selected={selected}>
				<CardHeader>
					{t('components.storyFormatCard.name', {
						name: format.name,
						version: format.version
					})}
				</CardHeader>
				<CardBody>
					<StoryFormatCardDetails format={format} />
				</CardBody>
				<StoryFormatCardActions
					format={format}
					onSelect={onSelect}
					selected={selected}
				/>
			</ImageCard>
		</div>
	);
};
