// src/components/control/color-select.tsx
import * as React from 'react';
import {useTranslation} from 'react-i18next';
import classNames from 'classnames';
import {Icon} from '../image/icon/icon';
import {colors, Color} from '../../util/color';
import './color-select.css';

export interface ColorSelectProps {
	label: string;
	onChange: (value: Color) => void;
	value: Color;
}

export const ColorSelect: React.FC<ColorSelectProps> = props => {
	const {label, onChange, value} = props;
	const {t} = useTranslation();

	return (
		<span className="color-select">
			<label>
				<span className="label">{label}</span>
				<span className="control">
					<span className={classNames('proxy', value)}>
						<Icon icon="circle" />
					</span>
					<select
						onChange={e => onChange(e.target.value as Color)}
						value={value}
					>
						{colors.map(color => (
							<option key={color} value={color}>
								{t(`colors.${color}`)}
							</option>
						))}
					</select>
				</span>
			</label>
		</span>
	);
};

// src/components/control/color-select.vue
<template>
	<span class="color-select">
		<label>
			<span class="label"><slot></slot></span>
			<span class="control">
				<span :class="proxyClasses">
					<icon-image name="circle" />
				</span>
				<select @change="onChange" ref="select">
					<option
						v-for="color in colors"
						:key="color"
						:selected="color === value"
						:value="color"
					>
						<icon-image name="circle" />
						<span v-t="{path: `colors.${color}`}" />
					</option>
				</select>
			</span>
		</label>
	</span>
</template>

<script>
import IconImage from '../icon-image';
import './color-select.css';

const colors = ['none', 'red', 'orange', 'yellow', 'green', 'blue', 'purple'];

export default {
	components: {IconImage},
	computed: {
		colors: () => colors,
		proxyClasses() {
			return {
				proxy: true,
				[this.value]: true
			};
		}
	},
	methods: {
		onChange() {
			this.$emit('change', this.$refs.select.value);
		}
	},
	name: 'color-select',
	props: {
		value: {
			default: 'none',
			validator(value) {
				return colors.includes(value);
			}
		}
	}
};
</script>
