// src/components/container/button-bar.vue
<template>
	<div :class="classes"><slot></slot></div>
</template>

<script>
import './button-bar.css';

export default {
	computed: {
		classes() {
			return {
				'button-bar': true,
				[`orientation-${this.orientation}`]: true
			};
		}
	},
	name: 'button-bar',
	props: {
		orientation: {
			default: 'horizontal',
			type: String,
			validator: value => ['horizontal', 'vertical'].includes(value)
		}
	}
};
</script>

// src/components/container/button-bar/button-bar.tsx
import * as React from 'react';
import classNames from 'classnames';
import './button-bar.css';

export interface ButtonBarProps {
	orientation?: 'horizontal' | 'vertical';
}

export const ButtonBar: React.FC<ButtonBarProps> = props => (
	<div
		className={classNames(
			'button-bar',
			`orientation-${props.orientation ?? 'horizontal'}`
		)}
	>
		{props.children}
	</div>
);
