// src/components/marquee-selection/index.vue
<template>
	<div
		class="marquee-selection"
		v-if="startX !== null && startY !== null"
		:style="style"
	></div>
</template>
<script>
import domMixin from '../../util/vue-dom-mixin';
import './index.css';

export default {
	computed: {
		rect() {
			let result = {};

			if (this.startX < this.currentX) {
				result.left = this.startX;
				result.width = this.currentX - this.startX;
			} else {
				result.left = this.currentX;
				result.width = this.startX - this.currentX;
			}

			if (this.startY < this.currentY) {
				result.top = this.startY;
				result.height = this.currentY - this.startY;
			} else {
				result.top = this.currentY;
				result.height = this.startY - this.currentY;
			}

			return result;
		},
		style() {
			return {
				left: `${this.rect.left}px`,
				height: `${this.rect.height}px`,
				top: `${this.rect.top}px`,
				width: `${this.rect.width}px`
			};
		}
	},
	data: () => ({
		additive: false,
		currentX: null,
		currentY: null,
		startX: null,
		startY: null
	}),
	methods: {
		onStartDrag(event) {
			const parentRect = this.$el.parentNode.getBoundingClientRect();

			/*
			If the user is holding down shift or control, then this is an
			additive selection.
			*/

			this.additive = event.shiftKey || event.ctrlKey;
			this.startX = event.clientX - parentRect.left;
			this.startY = event.clientY - parentRect.top;
			this.currentX = this.startX;
			this.currentY = this.startY;
			this.on(window, 'mousemove', this.onFollowDrag);
			this.on(window, 'mouseup', this.onStopDrag);

			/*
			We emit an initial select event to reflect that the selection has
			begun, but with a zero-size rect. The practical effect is that to
			allow the user to click in an empty space to deselect everything.
			*/

			this.$emit('start-select', this.additive);
			this.$emit('select', {additive: this.additive, ...this.rect});

			event.preventDefault();
		},
		onFollowDrag(event) {
			const parentRect = this.$el.parentNode.getBoundingClientRect();

			this.currentX = event.clientX - parentRect.left;
			this.currentY = event.clientY - parentRect.top;
			this.$emit('select', {additive: this.additive, ...this.rect});
			event.preventDefault();
		},
		onStopDrag() {
			this.off(window, 'mousemove');
			this.off(window, 'mouseup');
			this.currentX = null;
			this.currentY = null;
			this.startX = null;
			this.startY = null;
		}
	},
	mixins: [domMixin],
	mounted() {
		/*
		This component only works in mouse-enabled environments. It would
		otherwise block the ability to scroll with a touch.
		*/

		this.on(this.$el.parentNode, 'mousedown', this.onStartDrag);
	},
	name: 'marquee-selection'
};
</script>

// src/components/marquee-selection/marquee-selection.tsx
import * as React from 'react';
import {deviceType} from 'detect-it';
import 'element-closest';
import {rectFromPoints, Point, Rect} from '../../util/geometry';
import './marquee-selection.css';

function relativeEventPosition(
	event: MouseEvent,
	container: HTMLElement
): Point {
	const containerRect = container.getBoundingClientRect();

	return {
		left: event.clientX - containerRect.left,
		top: event.clientY - containerRect.top
	};
}

export interface MarqueeSelectionProps {
	container: React.RefObject<HTMLElement>;
	ignoreEventsOnSelector?: string;
	onSelectRect: (rect: Rect, additive: boolean) => void;
}

export const MarqueeSelection: React.FC<MarqueeSelectionProps> = props => {
	const {container, ignoreEventsOnSelector, onSelectRect} = props;
	const [selecting, setSelecting] = React.useState(false);
	const [additive, setAdditive] = React.useState(false);
	const [start, setStart] = React.useState<Point>({left: 0, top: 0});
	const [current, setCurrent] = React.useState<Point>({left: 0, top: 0});

	// Listener for the beginning of a selection.

	React.useEffect(() => {
		if (container.current) {
			const currentContainer = container.current;
			const handleMouseDown = (event: MouseEvent) => {
				if (ignoreEventsOnSelector) {
					if (
						(event.target as HTMLElement)?.closest(
							ignoreEventsOnSelector
						)
					) {
						return;
					}
				}

				setAdditive(event.shiftKey || event.ctrlKey);
				setSelecting(true);
				setStart(relativeEventPosition(event, currentContainer));
				setCurrent(relativeEventPosition(event, currentContainer));
				onSelectRect(rectFromPoints(start, current), additive);
			};

			currentContainer.addEventListener('mousedown', handleMouseDown);

			return () =>
				currentContainer.removeEventListener(
					'mousedown',
					handleMouseDown
				);
		}
	}, [
		additive,
		container,
		current,
		ignoreEventsOnSelector,
		onSelectRect,
		start
	]);

	// Listeners while the selection is taking place.

	React.useEffect(() => {
		if (selecting) {
			if (container.current) {
				const currentContainer = container.current;
				const handleMouseMove = (event: MouseEvent) => {
					setCurrent(relativeEventPosition(event, currentContainer));
					onSelectRect(rectFromPoints(start, current), additive);
				};
				const handleMouseUp = () => {
					setSelecting(false);
					cleanUp();
				};
				const cleanUp = () => {
					window.removeEventListener('mousemove', handleMouseMove);
					window.removeEventListener('mouseup', handleMouseUp);
					document.body.classList.remove('marquee-selecting');
				};

				window.addEventListener('mousemove', handleMouseMove);
				window.addEventListener('mouseup', handleMouseUp);
				document.body.classList.add('marquee-selecting');
				return cleanUp;
			}
		}
	}, [additive, container, current, onSelectRect, selecting, start]);

	// This component only works in mouse-enabled environments. It would otherwise
	// block the ability to scroll with a touch.

	if (!selecting || deviceType === 'touchOnly') {
		return null;
	}

	return (
		<div
			className="marquee-selection"
			style={rectFromPoints(start, current)}
		/>
	);
};
